import { GetServerSideProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {
  Box,
  Grid,
  Avatar,
  Button,
  ListItem,
  TextField,
  Typography,
  ListItemAvatar,
} from '@material-ui/core'

import { Product } from '../../models/Product'
import styles from '../../styles/Home.module.css'

type Props = {
  product: Product
}

const ProductDetailPage = ({ product }: Props) => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Store - Pagamento</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Typography
        variant="h3"
        gutterBottom
        component="h1"
        color="textPrimary"
      >
        Checkout
      </Typography>
      <ListItem>
        <ListItemAvatar>
          <Avatar src={product.image_url} />
        </ListItemAvatar>
        <ListItemText
          primatry={product.name}
          secondary={`R$ ${product.price}`}
        />
      </ListItem>
      <Typography
        variant="h6"
        gutterBottom
        component="h2"
      >
        Pague com cartão de crédito
      </Typography>
      <form>
        <Grid container spacing={3}>
          <Grid item xs={12} md={6}>
            <TextField required label="Nome" fullWidth />
          </Grid>
          <Grid item xs={12} md={6}>
            <TextField
              required
              fullWidth
              label="Número do cartão"
              inputProps={{ maxLength: 16 }}
            />
          </Grid>
          <Grid item xs={12} md={6}>
            <TextField 
              required
              fullWidth
              label="CVV"
              type="number"
            />
          </Grid>
          <Grid item xs={12} md={6}>
            <Grid container spacing={3}>
              <Grid item xs={6}>
                <TextField 
                 required
                 fullWidth
                 type="number"
                 label="Expiração mês"
                />
              </Grid>
              <Grid item xs={6}>
                <TextField
                  required
                  fullWidth
                  type="number"
                  label="Expiração ano"
                />
              </Grid>
            </Grid>
          </Grid>
        </Grid>
        <Box marginTop={3}>
          <Button 
            fullWidth
            type="submit"
            color="primary"
            variant="contained"
          >
            Pagar
          </Button>
        </Box>
      </form>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps<Props, {slug: string}> = async (ctx) => {
  const { slug } = ctx.params
  const { data: product } = await http.get(`products/${slug}`)
  
  return {
    props: { product },
  }
}

export default ProductDetailPage
