import Head from 'next/head'
import Image from 'next/image'
import { Typography } from '@material-ui/core'

import { Product } from '../models/Product'
import styles from '../styles/Home.module.css'

const products: Product[] = [{
  id: 'uuid',
  name: 'Produto Teste',
  description: 'Lorem Ipsum',
  price: 99.99,
  image_url: 'https://source.unsplash.com/random?product',
  slug: 'produto-teste',
  created_at: '2021-07-08T22:55:00'
}]

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Listagem de Produtos</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Typography
        component="h1"
        variant="h3"
        color="textPrimary"
        gutterBottom
      >
        Produtos
      </Typography>
    </div>
  )
}
