import { GetServerSideProps } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import {
  Card,
  Grid,
  Button,
  CardMedia,
  Typography,
  CardContent,
  CardActions,
} from '@material-ui/core'

import http from '../http'
import { Product } from '../models/Product'
import styles from '../styles/Home.module.css'

type Props = {
  products: Product[]
}

const ProductListPage = ({ products }: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Listagem de Produtos</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Typography
        component="h1"
        variant="h3"
        color="textPrimary"
        gutterBottom
      >
        Produtos
      </Typography>
      <Grid container spacing={4}>
        {products.map(product => (
          <Grid 
            key={product.id}
            item
            xs={12}
            md={4}
          >
            <Card>
              <CardMedia
                image={product.image_url}
                style={{ paddingTop: "56%" }}
              />
              <CardContent>
                <Typography 
                  component="h2"
                  variant="h5"
                  gutterbottom="true"
                >
                  {product.name}
                </Typography>
              </CardContent>
              <CardActions>
                <Link 
                  href="/produtos/[slug]"
                  as={`/produtos/${product.slug}`}
                  passHref
                >
                  <Button 
                    size="small"
                    component="a"
                    color="primary"
                  >
                    Detalhes
                  </Button>
                </Link>
              </CardActions>
            </Card>
          </Grid>
        ))}
      </Grid>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const { data: products } = await http.get('products')
  
  return {
    props: { products }
  }
}

export default ProductListPage
