import Head from 'next/head'
import Image from 'next/image'
import {
  Card,
  Button,
  CardMedia,
  Typography,
  CardContent,
  CardActions,
} from '@material-ui/core'

import { Product } from '../models/Product'
import styles from '../styles/Home.module.css'

const products: Product[] = [{
  id: 'uuid',
  price: 99.99,
  name: 'Produto Teste',
  slug: 'produto-teste',
  description: 'Lorem Ipsum',
  image_url: 'https://source.unsplash.com/random?product',
  created_at: '2021-07-08T22:55:00'
}]

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Listagem de Produtos</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Typography
        component="h1"
        variant="h3"
        color="textPrimary"
        gutterBottom
      >
        Produtos
      </Typography>
      {products.map(product => (
        <Card key={product.id}>
          <CardMedia image={product.image_url} />
          <CardContent>
            <Typography 
              component="h2"
              variant="h5"
              gutterbottom="true"
            >
              {product.name}
            </Typography>
            <CardActions>
              <Button 
                size="small"
                component="a"
                color="primary"
              >
                Detalhes
              </Button>
            </CardActions>
          </CardContent>
        </Card>
      ))}
    </div>
  )
}
